version: "3.9"

services:
  frontend:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: taskriver-frontend
    ports:
      - "127.0.0.1:3000:80"
    restart: always
